import type { Course } from '@/types';

export const sampleCourses: Course[] = [
  {
    id: '1',
    title: 'Ethical Hacking Masterclass',
    description: 'Complete guide to ethical hacking from beginner to advanced. Learn penetration testing, vulnerability assessment, and more.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=250&fit=crop',
    domain: 'Ethical Hacking',
    level: 'Advanced',
    instructorId: 'inst1',
    instructorName: 'Alex Security',
    price: 4999,
    tags: ['hacking', 'pentesting', 'kali linux'],
    modules: [],
    studentsEnrolled: 12450,
    rating: 4.9,
    reviewCount: 2340,
    status: 'published',
    createdAt: '2025-01-15',
    updatedAt: '2025-03-01',
  },
  {
    id: '2',
    title: 'Web Application Security',
    description: 'Learn to secure web applications from OWASP Top 10 vulnerabilities and beyond.',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=250&fit=crop',
    domain: 'Cyber Security',
    level: 'Intermediate',
    instructorId: 'inst2',
    instructorName: 'Sarah White',
    price: 3999,
    tags: ['web security', 'owasp', 'xss', 'sql injection'],
    modules: [],
    studentsEnrolled: 8920,
    rating: 4.8,
    reviewCount: 1560,
    status: 'published',
    createdAt: '2025-02-01',
    updatedAt: '2025-03-05',
  },
  {
    id: '3',
    title: 'Network Security Fundamentals',
    description: 'Master network security concepts including firewalls, IDS/IPS, and secure architectures.',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
    domain: 'Cyber Security',
    level: 'Basic',
    instructorId: 'inst3',
    instructorName: 'Mike Chen',
    price: 2499,
    tags: ['networking', 'firewalls', 'ids'],
    modules: [],
    studentsEnrolled: 15670,
    rating: 4.7,
    reviewCount: 3200,
    status: 'published',
    createdAt: '2025-01-01',
    updatedAt: '2025-02-15',
  },
  {
    id: '4',
    title: 'Malware Analysis & Reverse Engineering',
    description: 'Deep dive into malware analysis, reverse engineering binaries, and threat intelligence.',
    thumbnail: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=400&h=250&fit=crop',
    domain: 'Cyber Security',
    level: 'Advanced',
    instructorId: 'inst4',
    instructorName: 'David Black',
    price: 5999,
    tags: ['malware', 'reverse engineering', 'threat intelligence'],
    modules: [],
    studentsEnrolled: 6340,
    rating: 4.9,
    reviewCount: 890,
    status: 'published',
    createdAt: '2025-01-20',
    updatedAt: '2025-03-10',
  },
  {
    id: '5',
    title: 'Bug Bounty Hunting Pro',
    description: 'Learn professional bug bounty hunting techniques used by top researchers.',
    thumbnail: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=400&h=250&fit=crop',
    domain: 'Bug Bounty',
    level: 'Intermediate',
    instructorId: 'inst5',
    instructorName: 'Lisa Hunt',
    price: 3499,
    tags: ['bug bounty', 'hackerone', 'bugcrowd'],
    modules: [],
    studentsEnrolled: 9870,
    rating: 4.8,
    reviewCount: 1780,
    status: 'published',
    createdAt: '2025-02-10',
    updatedAt: '2025-03-12',
  },
  {
    id: '6',
    title: 'Cloud Security (AWS/Azure)',
    description: 'Secure cloud environments on AWS and Azure with best practices and hands-on labs.',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
    domain: 'AWS',
    level: 'Advanced',
    instructorId: 'inst6',
    instructorName: 'John Cloud',
    price: 4499,
    tags: ['aws', 'azure', 'cloud security'],
    modules: [],
    studentsEnrolled: 7230,
    rating: 4.6,
    reviewCount: 1120,
    status: 'published',
    createdAt: '2025-01-25',
    updatedAt: '2025-03-08',
  },
  {
    id: '7',
    title: 'AI & Machine Learning Fundamentals',
    description: 'Introduction to artificial intelligence and machine learning algorithms.',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop',
    domain: 'Artificial Intelligence',
    level: 'Basic',
    instructorId: 'inst7',
    instructorName: 'Dr. Priya AI',
    price: 2999,
    tags: ['ai', 'machine learning', 'python'],
    modules: [],
    studentsEnrolled: 11200,
    rating: 4.7,
    reviewCount: 2100,
    status: 'published',
    createdAt: '2025-02-05',
    updatedAt: '2025-03-01',
  },
  {
    id: '8',
    title: 'SOC Analyst Training',
    description: 'Become a Security Operations Center analyst. Learn SIEM, threat detection, and incident response.',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
    domain: 'SOC Analyst',
    level: 'Intermediate',
    instructorId: 'inst8',
    instructorName: 'Raj SOC',
    price: 3999,
    tags: ['soc', 'siem', 'incident response'],
    modules: [],
    studentsEnrolled: 5600,
    rating: 4.5,
    reviewCount: 780,
    status: 'published',
    createdAt: '2025-02-15',
    updatedAt: '2025-03-14',
  },
];
